### ISSUE TITLE
Better loot in dungeon chests.

### ISSUE THREAD

**Issue by Naenshiko** [CryptechTest/cryptech#103]
Improve the loot found in the dungeons, the loot will improve depending on how deep it is, with this we encourage exploration of these.

**Comment by Naenshiko** [comment]
Here is a basic list of the items that can be found in the chests..
The probability increases depending on the depth, if there is an object that you want to add, you are free to ask for it.

https://1drv.ms/x/s!AouX76m3f6clgRBWxDy-2zD809eG?e=bYF76m

**Comment by SeqSEE** [comment]
Just need to add TestCoin to loot table.
