### ISSUE TITLE
New awards.

### ISSUE THREAD

**Issue by Naenshiko** [CryptechTest/cryptech#109]
Add new awards.
To motivate users or give them an idea of ​​what they can get.

Here somes:
https://1drv.ms/x/s!AouX76m3f6clgRmzSwQl3I7g4NHm?e=gC4RRy

**Comment by squidicuzz** [comment]
How is this coming along?

**Comment by SeqSEE** [comment]
Base awards added. Will open an issue to modify and adjust them more during beta.
