### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by squidicuzz** [CryptechTest/cryptech#116]
Lag spikes in Orbital Station... This is a big performance issue.  Causes doors to not open and a host of other issues...

Packets spike from 5-20 ... to over 200 a tick.

*Investigation underway.*

**Comment by squidicuzz** [comment]
Issue is caused by ABM from the Vents/Air Handlers, and the Vacuum ABM's themselves... The function `has_in_range` is slow!

All of the vacuum/atmos air handling needs to be reworked, to reduce the amount of node updates, and ABM work.

**Comment by SeqSEE** [comment]
![profile1](https://github.com/CryptechTest/cryptech/assets/15011102/3e88e66c-01b1-454b-aea4-9b5c9dd3b542)

**Comment by squidicuzz** [comment]
@Naenshiko reworked the venting and wiring in the Orbital Station.  It is much better now!  ❤️
