### ISSUE TITLE
Some kind of death bug

### ISSUE THREAD

**Issue by ANormalStick** [CryptechTest/cryptech#117]
Was pillaring with messe blocks while it was dmging me, and then I got put into my bone death inventory and didnt get the respawn screen. Now I'm a walking god that cant get hurt or do anything but I can dmg other people. 
![image](https://github.com/CryptechTest/cryptech/assets/71927186/254e11f6-b204-4a1a-af91-0b71d4495e55)

**Comment by squidicuzz** [comment]
> That is not dead which can eternal lie,
And with strange aeons even death may die..

![image](https://github.com/CryptechTest/cryptech/assets/1578496/7b4510f5-da2a-4502-8f7e-b235df0a2207)
