### ISSUE TITLE
Nerf Rope (vines)

### ISSUE THREAD

**Issue by Naenshiko** [CryptechTest/cryptech#125]
This string needs to be nerfed as it can stretch infinitely.

![Screenshot_14](https://github.com/CryptechTest/cryptech/assets/43541892/9cad4333-bf99-41e3-ac39-76b60e69950c)

**Comment by SeqSEE** [comment]
Fixed in https://github.com/CryptechTest/plantlife_modpack/commit/3486a3212424fd40db5ff3169fba3fc73bc194b4
