### ISSUE TITLE
You cant see the water in the asteroid atmosphere..

### ISSUE THREAD

**Issue by Naenshiko** [CryptechTest/cryptech#129]
![image](https://github.com/CryptechTest/cryptech/assets/43541892/cc800210-82f4-4d24-9394-22a1b27cfa1e)

The only way to see it is to put a block on top of it.

**Comment by squidicuzz** [comment]
Interesting..

**Comment by squidicuzz** [comment]
fixed.. it will replace nearby with atmos_thick, which lets you see the water..
