### ISSUE TITLE
Remove mobs fence

### ISSUE THREAD

**Issue by SeqSEE** [CryptechTest/cryptech#16]
![image](https://user-images.githubusercontent.com/15011102/227452438-570701b7-63a7-488e-9f11-45306894dc3e.png)
![image](https://user-images.githubusercontent.com/15011102/227452580-5059831e-d7f4-400a-8bfb-40848ea00e22.png)

I propose to remove `mobs:fence` and `mobs:fence_top`

**Comment by squidicuzz** [comment]
changed plugins... not issue now.
