### ISSUE TITLE
Players should suffocate when stuck inside a solid node

### ISSUE THREAD

**Issue by squidicuzz** [CryptechTest/cryptech#19]
Currently players do not take damage (suffocate) when stuck inside of a solid block/node.  I propose that players do take damage when stuck inside surrounding solid nodes.

Examples of this include falling blocks (such as sand) will fall and bury the player, but the player does not take any damage due to this.

**Comment by ANormalStick** [comment]
Could be a fix - https://forum.minetest.net/viewtopic.php?f=9&t=15304

**Comment by ANormalStick** [comment]
@squidicuzz Could be a fix - https://forum.minetest.net/viewtopic.php?f=9&t=15304

**Comment by squidicuzz** [comment]
> @squidicuzz Could be a fix - https://forum.minetest.net/viewtopic.php?f=9&t=15304

Nice! This looks like what we need.
