### ISSUE TITLE
More layers of space

### ISSUE THREAD

**Issue by SeqSEE** [CryptechTest/cryptech#2]
More layers of space should be added to the other_worlds mod.

Each layer should be visually identifiable by the skybox and also have different generation settings and/or gravity.

**Comment by squidicuzz** [comment]
I improved how vacuum works in space... https://github.com/CryptechTest/cryptech/commit/5eb272b3da945e88be6fbc95d672ffb24b9eeb4b

**Comment by squidicuzz** [comment]
Update biomes for each layer of space/atmos.  updated skybox

**Comment by squidicuzz** [comment]
This is complete.
