### ISSUE TITLE
Node Protections

### ISSUE THREAD

**Issue by squidicuzz** [CryptechTest/cryptech#21]
We need a way to protect groups of nodes from modifications, such as the spawn area of the server.  Nothing too complicated, but this would be good to have..

**Comment by ANormalStick** [comment]
@squidicuzz Possible fix - https://notabug.org/TenPlus1/protector/src/master/README.md

**Comment by SeqSEE** [comment]
> @squidicuzz Possible fix - https://notabug.org/TenPlus1/protector/src/master/README.md

this is the same one I was looing at

**Comment by SeqSEE** [comment]
We're testing out protector. It doesn't seem like it fully protects, so we will need to look into which mods do not respect the protection.

**Comment by squidicuzz** [comment]
Seems good to me!  Added.
