### ISSUE TITLE
Space station as world spawn

### ISSUE THREAD

**Issue by SeqSEE** [CryptechTest/cryptech#3]
Add a space station near world height limit as the starting point for new players and players who have not set their home.

**Comment by squidicuzz** [comment]
We will need to protect the spawn area as well... I open #21 for this.

**Comment by squidicuzz** [comment]
Station is built.  Needs import into world...

**Comment by squidicuzz** [comment]
Complete!  Station loads on first load...

Might need to break the jumpdrive, above spawn... *to reset and fix.*
