### ISSUE TITLE
Texture & Icon Changes

### ISSUE THREAD

**Issue by Kyuhisan** [CryptechTest/cryptech#42]
Issue to keep track of textures, icons and other UI elements that need changing to fit the broad theme.
**Keep the textures in 16x16 or 32x32 pixels**

- [x] - Jungle Wood
- [x] - Large Bag
- [x] - Medium Bag
- [x] - Small Bag
- [x] - Atmosphere (atmos)
- [x] - Air Bottle (fixed the cap color)
- [ ] - Bottler
- [x] - Armor icon & preview fixes

**Notes:**
**Jungle Wood -** It would be ideal to change the design of the bark of these trees since aesthetically it does not look so good... the planks, on the contrary, are very good in terms of their color.

**Bags**
Replace the textures for bags from unified_inventory

**Comment by squidicuzz** [comment]
I improved the "atmosphere" texture for border between vacuum.  It is more transparent now.

**Comment by squidicuzz** [comment]
Also, earlier... I updated the `air bottle` texture..

**Comment by Kyuhisan** [comment]
Updated the textures for bags_small, bags_medium, bags_large and ui_bags_icon


![bags_small](https://user-images.githubusercontent.com/64851536/229957799-e3738864-ec0b-4444-a0a3-525b37af3a18.png)
![bags_medium](https://user-images.githubusercontent.com/64851536/229957802-5b746790-9b6f-4a51-abb8-a68b7e10dff3.png)
![bags_large](https://user-images.githubusercontent.com/64851536/229957803-1b193b35-6857-4d8b-9458-be36fbb0fdc8.png)
![ui_bags_icon](https://user-images.githubusercontent.com/64851536/229957804-2c86b906-d87d-4a60-a931-0f39b64fb345.png)

**Comment by squidicuzz** [comment]
Armor needs the "preview" texture fixed.  It doesn't cover the player entirely...
![image](https://user-images.githubusercontent.com/1578496/230071543-bb65365a-3069-4e00-9f1c-82c7add3e477.png)

**Comment by squidicuzz** [comment]
> 

I updated the project repo with these.

**Comment by squidicuzz** [comment]
> Updated the textures for bags_small, bags_medium, bags_large and ui_bags_icon
> 
> ![bags_small](https://user-images.githubusercontent.com/64851536/230018117-a4b518db-416b-44e4-bd5c-4ce6f9ad2c53.png) ![bags_large](https://user-images.githubusercontent.com/64851536/230018121-bfb47630-931d-497d-8add-08d42624cea5.png) ![ui_bags_icon](https://user-images.githubusercontent.com/64851536/230018122-49fe3b76-7e22-4a62-b19e-4e490cb7a93f.png) ![bags_medium](https://user-images.githubusercontent.com/64851536/230018126-b8827475-3285-41e2-92a2-e3bee1d99e89.png)

I updated the project repo with these.

**Comment by Kyuhisan** [comment]
> Armor needs the "preview" texture fixed. It doesn't cover the player entirely... ![image](https://user-images.githubusercontent.com/1578496/230071543-bb65365a-3069-4e00-9f1c-82c7add3e477.png)

Fixed the textures for armor and adjusted armor icons for certain items

**Comment by squidicuzz** [comment]
closing this... i'll adjust bottler later.
