### ISSUE TITLE
Multiple watermelon

### ISSUE THREAD

**Issue by SeqSEE** [CryptechTest/cryptech#46]
Need to make the watermelon compatible

**Comment by ANormalStick** [comment]
???

**Comment by SeqSEE** [comment]
![image](https://user-images.githubusercontent.com/15011102/231366906-b8b967a2-d9a5-42bf-989a-bdc9761ae5bc.png)
![image](https://user-images.githubusercontent.com/15011102/231366953-a5e169a1-8dfa-47d0-ab09-bd51cfac76b6.png)
![image](https://user-images.githubusercontent.com/15011102/231367005-1ecb5d00-845e-4e9b-ab35-70e15d413ec0.png)
![image](https://user-images.githubusercontent.com/15011102/231367090-be8a5af3-2e73-4192-b1a8-29bfacd40321.png)
![image](https://user-images.githubusercontent.com/15011102/231367211-ef4ea94e-e30d-4e06-93f6-09aa102a6cd6.png)
![image](https://user-images.githubusercontent.com/15011102/231367251-f6f3435b-e571-46b8-8273-443ddb40cf15.png)


There is multiple melon

**Comment by SeqSEE** [comment]
I personally think the melon from `x_farming` is better than the one from `crops`

**Comment by SeqSEE** [comment]
I think we should actually just remove `crops` looking at it.

**Comment by SeqSEE** [comment]
`crops` removed
