### ISSUE TITLE
Jet Packs

### ISSUE THREAD

**Issue by SeqSEE** [CryptechTest/cryptech#47]
- [x] Create a new Armor Element jetpack. 
- [x] Add different levels of jetpacks with different stats like fuel capacity and alternative power sources
  - [x] Copper (Steam powered)
  - [x] Iron (Fuel powered)
  - [x] Titanium (Hydrogen powered)
  - [x] Solar backup upgrade (upgrade to give a limited amount of solar backup)
- [x] Change the action to enable and disable to double jump while in the air, similar to the Elytra from Minecraft.

**Comment by squidicuzz** [comment]
Need to come up with fuel recipes still...

Crafting recipes for the Jetpack itself now exist.

**Comment by squidicuzz** [comment]
New jetpacks implemented:
![image](https://user-images.githubusercontent.com/1578496/229910086-7e7c4d95-ad59-4a5e-bb7e-c7d4b1c443f3.png)

**Comment by squidicuzz** [comment]
Jetpacks are much better now.  🚀
