### ISSUE TITLE
Jetpack doesn't teleport with you

### ISSUE THREAD

**Issue by squidicuzz** [CryptechTest/cryptech#62]
Jetpack entity does not teleport with the player when they teleport.. it gets left behind.

Taking off the jetpack and equipping it again, fixes things.

**Comment by SeqSEE** [comment]
Sounds like it can be solved by unequipping before teleport and then equipping the jetpack after teleport?

**Comment by squidicuzz** [comment]
I looked into this a bit... the teleport thing in minetest, is just `player:set_pos()`  and there is no normal `teleport` event...

I also tried to teleport with the jetport, and could not reproduce this bug.  😖

**Comment by squidicuzz** [comment]
Well, the pickaxe has the same issue... sooo... whatever?  It'll work itself out!
