### ISSUE TITLE
Jetpack dupe

### ISSUE THREAD

**Issue by ANormalStick** [CryptechTest/cryptech#8]
Upon dying with a jetpack on you, you will respawn with it still on.

**Comment by SeqSEE** [comment]
We're going to be redoing (or creating a new) jetpack mod.

The mod will:

- Create a new Armor Element `jetpack`
- Add different levels of jetpacks with different stats like fuel capacity and alternative power sources
- Change the action to enable and disable to double jump while in the air, similar to the Elytra from Minecraft.

**Comment by SeqSEE** [comment]
See #47
