### ISSUE TITLE
Cut Grass bug

### ISSUE THREAD

**Issue by ANormalStick** [CryptechTest/cryptech#82]
Cut Grass stacks like carpet from minecraft, it should be not walkable and be only placed on walkable nodes.
![image](https://user-images.githubusercontent.com/71927186/232854871-ae792777-42ea-4d98-b626-bd1cdc4c1a0a.png)
Savanna grass and other dry type of grasses need to make "hay" not cut grass when used with sickle

**Comment by ANormalStick** [comment]
https://github.com/mt-mods/plantlife_modpack/commit/f91f708a23727f50e3f7a29fc52e54284f70a35c

**Comment by ANormalStick** [comment]
[https://github.com/mt-mods/plantlife_modpack/commit/f91f708a23727f50e3f7a29fc52e54284f70a35c](url)

**Comment by SeqSEE** [comment]
merged
