### ISSUE TITLE
Rework vehicle recipes

### ISSUE THREAD

**Issue by SeqSEE** [CryptechTest/cryptech#89]
Rework the recipes from  `vehicle_mash` to be a bit more realistic than wool for everything.
![image](https://user-images.githubusercontent.com/15011102/233530341-360479a8-07e6-442b-a1ef-6194cc916b84.png)

For example the battery could be improved
current:
![image](https://user-images.githubusercontent.com/15011102/233670415-f81fd495-b019-4947-87c8-a9e09538ad83.png)

proposed:
L = lead ingot
i = iron ingot
s = sulfur lump
r = red dye
b = blue dye
w = water bucket group
```
b | L | r
i | s | i
i | w | i
```
![image](https://user-images.githubusercontent.com/15011102/233671747-f7d06070-cb13-41f2-aa6c-6186ed3d79e6.png)

**Comment by SeqSEE** [comment]
![image](https://user-images.githubusercontent.com/15011102/233675075-b79787ff-80c6-4144-b774-84a65396b0c4.png)
![image](https://user-images.githubusercontent.com/15011102/233675395-699b1150-1590-48ac-9cda-91e89ce702c9.png)

**Comment by SeqSEE** [comment]
To add to this would be nice to have the wrench able to repair the vehicles (if they don't already)

**Comment by SeqSEE** [comment]
![image](https://user-images.githubusercontent.com/15011102/233684870-2f58222d-0764-4262-b8b1-f4dccbc3b058.png)
![image](https://user-images.githubusercontent.com/15011102/233685326-acb4bc61-0af8-442a-a679-05621e40086c.png)

**Comment by Vanikoro** [comment]
I like those recipes, have sense to me
