### ISSUE TITLE
Bug beds / respawn in the space.

### ISSUE THREAD

**Issue by Naenshiko** [CryptechTest/cryptech#92]
-By breaking the last bed in which you spawns when you die you can appear again in space with the starter kit..
![Screenshot_2](https://user-images.githubusercontent.com/43541892/233699505-95ea403f-54e0-4ce4-8c69-8fe1a2ff04f5.png)
![Screenshot_3](https://user-images.githubusercontent.com/43541892/233699561-77182172-e8ae-462d-ba86-8891eb2bdc79.png)
![Screenshot_4](https://user-images.githubusercontent.com/43541892/233699661-bb7462b6-db5e-4557-9a58-0f3930304184.png)
The bug only happens when you go to sleep at night.

**Comment by SeqSEE** [comment]
fixed bug by picking the first available bed spawn when the bed is destroyed.
